compartment_id="ocid1.compartment.oc1..aaaaaaaa66gbdyhlvqetu4jrxh7ijkjvemi7fk5uyawc274yrs2xbab2sl4q"
db_system_credentials_password_details_password=""
db_system_credentials_username="admin"
source_operating_system_image_id="ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa5ww2sv5lpmouczvhp3e3udhrpngoribmotinvw734lti2avkktwa"
